# Generated by Django 4.2.1 on 2023-06-09 05:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("context", ckeditor.fields.RichTextField()),
                ("date_publish", models.DateTimeField(auto_now=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="if leave it will take from title ",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="if leave it will take from title ",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "meta_keywords",
                    models.TextField(
                        blank=True, help_text="use comma( , ) for separation", null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pages.category",
                    ),
                ),
            ],
        ),
    ]
