# Generated by Django 4.2.1 on 2023-06-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="why_choose",
        ),
        migrations.AlterField(
            model_name="whychoose",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="whychoose",
            name="title",
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name="homepage",
            name="why_choose",
            field=models.ManyToManyField(to="home.whychoose"),
        ),
    ]
