# Generated by Django 4.2.1 on 2023-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_homepage_why_choose_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whychoose",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="whychoose"),
        ),
    ]
